include ../makefile-variables.mk

SRCS += 08-button-bare.c

LIB_SRCS += 

HDRS = 

# See ST UM1785 "Description of STM32F0 HAL and low-layer drivers"
# CFLAGS += -DUSE_FULL_LL_DRIVER 

include ../makefile-targets.mk
